ignoredBuiltDependencies:
  - '@tailwindcss/oxide'
  - sharp

onlyBuiltDependencies:
  - unrs-resolver

overrides:
  glob@>=10.2.0 <10.5.0: '>=10.5.0'
  js-yaml@<3.14.2: '>=3.14.2'
  tar@=7.5.1: '>=7.5.2'
